### ISSUE TITLE
T1-D4 Uploaded

### ISSUE THREAD

**Issue by brkye** [CS319-23-SP/T1-havuz#23]
It is in Docs file, in 2 parts.

**Comment by SahandMoslemi** [comment]
Dear @CS319-23-SP/t1-havuz 
First feedback to your D4 is as follows:

- [x] Please add headings for Connectors, Architectural Style and Design Goals.
- [x] Connectors.
- [x] Subsystem Decomposition Diagram.
  - [x] Some functionalities are missing in the diagram. (e.g. Admin only has access to student CRUD Interface.) 
  - [x] A subsystem decomposition diagram is intended to make a complex system easier to understand. There is no need to specify authentication or other permission-related steps in this diagram. Instead, try to develop a hierarchy to explain your complex system more clearly. 
- [x] Architectural Style.
- [x] Design Goals.
